export const flags = [
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/AR.svg", label: "Argentina" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/BZ.svg", label: "Belice" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/BO.svg", label: "Bolivia" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/BR.svg", label: "Brasil" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/CA.svg", label: "Canadá" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/CL.svg", label: "Chile" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/CO.svg", label: "Colombia" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/CR.svg", label: "Costa Rica" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/CU.svg", label: "Cuba" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/CW.svg", label: "Curazao" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/DM.svg", label: "Dominica" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/DO.svg", label: "República Dominicana" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/EC.svg", label: "Ecuador" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/SV.svg", label: "El Salvador" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/ES.svg", label: "España" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/US.svg", label: "Estados Unidos" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/FR.svg", label: "Francia" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/GD.svg", label: "Granada" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/GR.svg", label: "Grecia" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/GP.svg", label: "Guadalupe" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/GT.svg", label: "Guatemala" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/GY.svg", label: "Guyana" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/HT.svg", label: "Haití" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/HN.svg", label: "Honduras" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/IT.svg", label: "Italia" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/JM.svg", label: "Jamaica" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/JP.svg", label: "Japón" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/MQ.svg", label: "Martinica" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/MX.svg", label: "México" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/MS.svg", label: "Montserrat" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/NI.svg", label: "Nicaragua" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/NL.svg", label: "Países Bajos" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/PA.svg", label: "Panamá" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/PY.svg", label: "Paraguay" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/PE.svg", label: "Perú" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/PT.svg", label: "Portugal" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/PR.svg", label: "Puerto Rico" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/GB.svg", label: "Reino Unido" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/DO.svg", label: "República Dominicana" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/KN.svg", label: "San Cristóbal y Nieves" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/SM.svg", label: "San Marino" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/VC.svg", label: "San Vicente y las Granadinas" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/SE.svg", label: "Suecia" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/CH.svg", label: "Suiza" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/SR.svg", label: "Surinam" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/TT.svg", label: "Trinidad y Tobago" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/TR.svg", label: "Turquía" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/UA.svg", label: "Ucrania" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/UY.svg", label: "Uruguay" },
  { value: "https://purecatamphetamine.github.io/country-flag-icons/3x2/VE.svg", label: "Venezuela" },
];
