export const config = {
  theme: "dark",
  readonly: false,
  minHeight: "250px",
  allowResizeY: false,
  buttons: [
    "font",
    "fontsize",
    "|",
    "bold",
    "italic",
    "underline",
    "eraser",
    "|",
    "ul",
    "ol",
    "|",
    "brush",
    "table",
    "left",
    "center",
    "right",
    "justify",
  ],
  removeButtons: [
    "source",
    "|",
    "brush",
    "|",
    "|",
    "paragraph",
    "|",
    "image",
    "link",
    "|",
    "|",
    "undo",
    "redo",
    "|",
    "hr",
    "fullsize",
    "copyformat",
    "source",
  ],
  enter: "div",
  showXPathInStatusbar: false,
  showCharsCounter: false,
  showWordsCounter: false,
  toolbarAdaptive: false,
  toolbarSticky: true,
  autofocus: false,
  addNewLine: false,
  saveSelectionOnBlur: false,
  askBeforePasteHTML: false,
  cursorAfterAutofocus: "end",
  askBeforePasteFromWord: false,
  defaultActionOnPaste: "insert_only_text",
  defaultActionOnPasteFromWord: "insert_only_text",
  style: {
    background: "#1B1C1B",
    maxWidth: "500px",
    overflow: "auto",
    maxHeight: "171px",
    
  },
};
